### ISSUE TITLE
Include package.json file

### ISSUE THREAD

**Issue by Anonyfox** [seagull-js/build-tools#2]
Something like https://github.com/browserify/brfs could be used to include the package.json file from seagull aps into the browser bundle, solving a bunch of issues of the package-config module.

**Comment by Harper04** [comment]
We used brfs before for pages and stores, but removed it to stay away from hard browserify specific AST transforms. 
(We used some environment detection instead and choosed from a bunch of hard paths )

In this case i think brfs would not be able to infer `process.cwd()` so we would have to use paths anyway...

**Comment by Harper04** [comment]
possible approaches (from ugly to less likely possible):
* using paths (see below)
* using ts/sed transform to require the config in our created index.js (the one collecting pages/stores 
could place it in a seagull window object where package conf can pick it up...
-> only defering our paths to the routing/page/store class and introducing a global
* using a environment variable which holds process.cwd, hoping this would be staticly analyzable on bundling
lambda path is known, cli could set it for tests and dev serving


this is below:
current way
```
  private requireIndexByEnv() {
    if (process && process.env && process.env.LAMBDA_TASK_ROOT && process.env.AWS_EXECUTION_ENV) {
      return require('/var/task/dist/frontend/index.js')
    }
    if (process && process.env && process.env.NODE_ENV === 'test') {
      return require('../../../../../../__tmp__/.seagull/dist/frontend/index.js')
    }
    return require('../../../../../../.seagull/dist/frontend/index.js')
  }
```
more streamlined
```
  private requireIndexByEnv() {
    const isLambdaEnv = !get(process, 'env.LAMBDA_TASK_ROOT')
    const isTestEnv = get(process, 'env.NODE_ENV') === 'test'
    if ( !isLambdaEnv && !isTestEnv) {
      return require('../../../../../../.seagull/dist/frontend/index.js')
    }
    let cwd = process.cwd().toString()
    isTestEnv ? (cwd = join(cwd, '.seagull')) : noop()
    return require(join(cwd, 'dist', 'frontend', 'index.js'))
  }
```

**Comment by Anonyfox** [comment]
can't we just "polyfill" a `process.cwd = () => return $PATH` somewhere before the bundle happens? just an idea. AFAIK the `process` global is already polyfilled by browserify

**Comment by Harper04** [comment]
we could try that,
at least setting process.env.PATH should work with envify

**Comment by Harper04** [comment]
or: as we use SSR we could hydrate the browser config from server (where everything is working)

**Comment by Harper04** [comment]
or: breaking our 'architectural circle'. (@seagull/core loads things from the users project folder)
-> moving client entry from core to build-tool-generated version in .seagull
-> bundling would link to that instead
-> could load index and package json with a now very well known path
-> call new PackageJSON(requiredPackageJSON)

implications:
PackageJSON has to be a singleton
Routing.tsx in core should work the same way and has to be rewritten

problems:
SSR has to import the backend entry which should work the same way.
But this file does not exist at that point yet. (Also generating Frontend.ts ?...)

**Comment by Anonyfox** [comment]
could we fold the packageJSON loading into the general application-loader (WIP) package and use this from the build-tools? Using this package as the starting point, a new Routing.tsx may be implemented simpler

**Comment by Harper04** [comment]
Yes that would be a good starting point, but i think the underlying question how this would work internally persists
